#!/usr/bin/bash


sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
sudo apt-get install python3
sudo apt-get install python-is-python3
sudo apt-get install pip
sudo apt-get install python3-venv
python3 -m venv VenvNotlar
source VenvNotlar/bin/activate
python3 --version > python 
pip install pandas
deactivate

mkdir -p ~/github/NotDefteri
sudo rm -rf /usr/bin/notlar
sudo cp -r notlar /usr/bin/notlar
sudo chmod 777 /usr/bin/notlar
cp -r * ~/github/NotDefteri/


echo "Yükleme işlemi tamamlandı. Çalıştırmak için terminale 'notlar' yazın"
