#!/usr/bin/bash



sudo apt-get install python3
sudo apt-get install pip 
pip install pandas

mkdir -p ~/github/NotDefteri
sudo cp -r notlar /usr/bin/notlar
sudo chmod 777 /usr/bin/notlar
cp -r * ~/github/NotDefteri/notlar


echo "Yükleme işlemi tamamlandı. Çalıştırmak için terminale 'notlar' yazın"
